baseURL = "/"
languageCode = "en-us"
title = "almo7aya.dev"
theme = "cactus"
copyright = "Almo7aya" # cactus will use title if copyright is not set
disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set
googleAnalytics = "G-KLG0T39J77"
author = "Almo7aya"
disableKinds = ["taxonomy", "taxonomyTerm"]

summaryLength = 2

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "gruvbox"
    tabWidth = 4

[params]
  colortheme = "dark" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = true # default
  avatar = "/images/avatar.jpg"
  tocInline = false

  # Home page settings
  description = "Senior web engineer supercharged with typescript, rust, and lua, with hands-on experience in various technologies, Working @ [anghami](https://anghami.com)."
  mainSection = "posts" # your main section
  aboutSection = "about"
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/almo7aya" # title link for projects list

  footeremail = "alialmohaya@gmail.com"
  footergithub = "https://github.com/almo7aya"
  footertwitter = "https://twitter.com/almo7aya"
  footerlinkedin = "https://linkedin.com/in/almo7aya"

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default
  mainSectionTitle = "## Posts"

  [params.comments]
    enabled = true # default
    engine = "utterances" # only disqus, utterances, and cactus_comments is supported
    [params.comments.utterances]
      repo = "almo7aya/almo7aya.github.io"
      label = "almo7aya.dev" # you can use however you want to label your name in your repo's issues
      theme = "github-dark"
    [params.comments.cactuscomments]
      siteName = "your_cactus_comments_sitename" # see https://cactus.chat/ on how to register your site name
      #serverUrl = "" # Defaults to https://matrix.cactus.chat:8448 (Cactus Chat public server)
      #serverName = "" # Defaults to cactus.chat

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/almo7aya"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/almo7aya/"
  [[params.social]]
    name = "email"
    link = "alialmohaya@gmail.com"  # no need for "mailto:" in the head
