// os/programs/intro/assets.mjs · tables, palettes, pixels and music for 7INTRO
// everything that needs floating point is computed here and written into gen/:
//   tunnel.bin   320x100 words: low byte angle, high byte depth (clamped to 223)
//   girl.bin     still128 quantised to 64 levels (176..239), white background -> 0 (transparent)
//   panic.bin    the 16 panic64 frames, same treatment
//   song.bin     the PC speaker music: one PIT divisor per 70 Hz tick (0 = silent)
//   data.inc     palettes, star positions, the scroller text, song length
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

export const TICK_HZ = 1193182 / 17045;           // PIT channel 0 divisor 17045, ~70.0 Hz
const BAR = 112;                                   // 16 rows of 7 ticks
export const BARS = 70;

export default async ({ dir, gen, root, CP437 }) => {
  const db = (name, bytes) => `${name}:\n` + chunks([...bytes], 16).map(r => '        db ' + r.join(', ')).join('\n') + '\n';
  const dw = (name, words) => `${name}:\n` + chunks([...words], 12).map(r => '        dw ' + r.join(', ')).join('\n') + '\n';
  let inc = '; generated by assets.mjs\n';

  // ---------------- palettes (6-bit) ----------------
  const clamp = v => Math.max(0, Math.min(63, Math.round(v)));
  const lerp = (a, b, t) => a + (b - a) * t;
  const ramp = (stops, t) => {                     // stops: [[r,g,b], ...] evenly spaced, t 0..1
    const x = Math.max(0, Math.min(1, t)) * (stops.length - 1), i = Math.min(stops.length - 2, Math.floor(x)), f = x - i;
    return stops[i].map((c, k) => lerp(c, stops[i + 1][k], f));
  };
  const pal = () => Array.from({ length: 256 }, () => [0, 0, 0]);
  const flat = p => p.flatMap(c => c.map(clamp));

  // part 1 / 6: stars 16..47, text gradient 224..239
  const pStars = pal();
  for (let i = 0; i < 32; i++) { const v = Math.pow(i / 31, 1.3); pStars[16 + i] = [v * 52, v * 58, v * 63]; }
  for (let r = 0; r < 16; r++) pStars[224 + r] = ramp([[63, 63, 48], [63, 52, 20], [63, 24, 36], [40, 10, 50]], r / 15);

  // part 2: fire
  const pFire = pal();
  for (let h = 0; h < 256; h++) pFire[h] = [h * 63 / 80, (h - 70) * 63 / 90, (h - 170) * 63 / 70];

  // part 3: background 1..50, 7 copper bars 64..175, girl 176..239, text 240..255
  const pGirl = pal();
  for (let i = 1; i <= 50; i++) pGirl[i] = ramp([[2, 1, 10], [10, 2, 18], [3, 4, 14]], (i - 1) / 49);
  const barHue = [[63, 10, 10], [63, 34, 0], [63, 60, 8], [12, 60, 16], [0, 50, 63], [16, 20, 63], [52, 12, 63]];
  barHue.forEach((h, b) => { for (let s = 0; s < 16; s++) { const t = s / 15, w = Math.max(0, t - 0.75) * 4; pGirl[64 + b * 16 + s] = h.map(c => lerp(c * t, 63, w * 0.8)); } });
  for (let v = 0; v < 64; v++) pGirl[176 + v] = ramp([[1, 0, 6], [22, 6, 30], [52, 26, 48], [63, 60, 63]], v / 63);
  for (let r = 0; r < 16; r++) pGirl[240 + r] = ramp([[63, 63, 63], [30, 63, 63], [10, 40, 63]], r / 15);

  // part 4: tunnel, colour = shade * 32 + texel; 224 black, 240..255 text
  const pTun = pal();
  const bright = [1.0, 0.86, 0.7, 0.54, 0.38, 0.24, 0.12];
  for (let s = 0; s < 7; s++) for (let c = 0; c < 32; c++) {
    const m = c < 16 ? c / 15 : (31 - c) / 15;
    pTun[s * 32 + c] = ramp([[2, 6, 24], [24, 2, 40], [63, 8, 32], [63, 48, 16], [63, 63, 52]], m).map(v => v * bright[s]);
  }
  for (let r = 0; r < 16; r++) pTun[240 + r] = ramp([[63, 63, 63], [63, 60, 30], [63, 36, 8]], r / 15);

  // part 5: plasma 0..127 (cycled at runtime from plasma_cyc), logo 160..175 (from rainbow), scroller 192..207, shadow 208
  const pScroll = pal();
  for (let r = 0; r < 16; r++) pScroll[192 + r] = ramp([[63, 63, 63], [63, 58, 30], [63, 40, 10], [60, 20, 10]], r / 15);
  const cyc = Array.from({ length: 128 }, (_, i) => ramp([[4, 2, 16], [14, 4, 26], [4, 14, 26], [2, 22, 22], [10, 6, 24], [4, 2, 16]], i / 128));
  const rainbow = Array.from({ length: 64 }, (_, i) => { const a = i / 64 * 2 * Math.PI; return [32 + 31 * Math.sin(a), 32 + 31 * Math.sin(a + 2.1), 32 + 31 * Math.sin(a + 4.2)]; });

  inc += db('pal_stars', flat(pStars)) + db('pal_fire', flat(pFire)) + db('pal_girl', flat(pGirl)) +
    db('pal_tunnel', flat(pTun)) + db('pal_scroll', flat(pScroll)) + db('plasma_cyc', flat(cyc)) + db('rainbow', flat(rainbow));

  // ---------------- stars: x -512..511, y -320..319, z 1..255 ----------------
  let seed = 7;
  const rnd = () => (seed = (seed * 1103515245 + 12345) >>> 0) / 4294967296;
  const NSTARS = 320;
  const stars = [];
  for (let i = 0; i < NSTARS; i++) {
    const x = Math.round(rnd() * 1024 - 512), y = Math.round(rnd() * 640 - 320), z = 1 + Math.floor(rnd() * 255);
    stars.push(x & 0xFF, (x >> 8) & 0xFF, y & 0xFF, (y >> 8) & 0xFF, z);
  }
  inc += `NSTARS equ ${NSTARS}\n` + db('stars', stars);

  // ---------------- tunnel: 320 x 100 (each row covers two scanlines) ----------------
  const tun = Buffer.alloc(320 * 100 * 2);
  for (let row = 0; row < 100; row++) for (let x = 0; x < 320; x++) {
    const dx = x - 159.5, dy = (row * 2 + 1 - 100) * 1.2;
    const r = Math.hypot(dx, dy);
    const u = Math.floor((Math.atan2(dy, dx) / (2 * Math.PI) + 1) * 256) & 255;
    const d = Math.min(223, Math.floor(5200 / Math.max(r, 1)));
    tun[(row * 320 + x) * 2] = u; tun[(row * 320 + x) * 2 + 1] = d;
  }
  writeFileSync(join(gen, 'tunnel.bin'), tun);

  // ---------------- the girl ----------------
  const bayer = [[0, 8, 2, 10], [12, 4, 14, 6], [3, 11, 1, 9], [15, 7, 13, 5]];
  function girl(src, w, h) {                       // flood the white background from the border -> 0
    const out = Buffer.alloc(w * h), bg = new Uint8Array(w * h), q = [];
    const push = (x, y) => { const i = y * w + x; if (x < 0 || y < 0 || x >= w || y >= h || bg[i] || src[i] < 222) return; bg[i] = 1; q.push(i); };
    for (let x = 0; x < w; x++) { push(x, 0); push(x, h - 1); }
    for (let y = 0; y < h; y++) { push(0, y); push(w - 1, y); }
    while (q.length) { const i = q.pop(), x = i % w, y = (i / w) | 0; push(x + 1, y); push(x - 1, y); push(x, y + 1); push(x, y - 1); }
    for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) {
      const i = y * w + x;
      if (bg[i]) continue;
      const v = Math.max(0, Math.min(63, Math.floor((src[i] + (bayer[y & 3][x & 3] - 7.5) * 0.25) / 4)));
      out[i] = 176 + v;
    }
    return out;
  }
  writeFileSync(join(gen, 'girl.bin'), girl(readFileSync(join(root, 'os', 'assets', 'girl', 'still128.bin')), 128, 128));
  const panic = readFileSync(join(root, 'os', 'assets', 'girl', 'panic64.bin'));
  writeFileSync(join(gen, 'panic.bin'), Buffer.concat(Array.from({ length: 16 }, (_, f) => girl(panic.subarray(f * 4096, f * 4096 + 4096), 64, 64))));

  // ---------------- scroller text (only facts about Ali) ----------------
  const scroll = [
    'Hi! This is Ali Almohaya, aka Almo7aya',
    'Staff Web Engineer at Anghami & OSN+, building web and smart-TV streaming apps',
    'with a soft spot for video playback and DRM',
    'TypeScript, React, Node.js, C++, Go, Rust and Lua',
    'from Yemen, living in Riyadh',
    'beyond the web: low-level code, emulation and C++, just for fun',
    'projects:   PS5 Shader Lab, a C++20 shader regression tool',
    'Learning KytyPS5, a course on how a PS5 emulator works',
    'GoWAN, multi-WAN SOCKS5 in Go for OpenWrt',
    'openingh.nvim (163 stars) and neogruvbox.nvim',
    'merged patches in Preact, LunarVim, ani-cli and Live Server',
    'github.com/Almo7aya',
  ].join('  *  ');
  const bytes = [...scroll].map(ch => { const i = CP437.indexOf(ch); if (i < 0) throw new Error(`not in CP437: ${ch}`); return i; });
  // part 5 is 32 bars; the scroller moves 3 px per tick, 16 px per character, and starts off-screen right
  const budget = Math.floor((32 * BAR * 3 - 320) / 16);
  if (bytes.length > budget) throw new Error(`scroll text is ${bytes.length} chars, only ${budget} fit`);
  inc += `SCROLL_LEN equ ${bytes.length}\n` + db('scroll_text', bytes);

  // ---------------- music ----------------
  const hz = n => 440 * Math.pow(2, (n - 69) / 12);
  const N = s => { const m = s.match(/^([A-G])(#?)(\d)$/); return 12 * (+m[3] + 1) + 'C D EF G A B'.indexOf(m[1]) + (m[2] ? 1 : 0); };
  const chords = [['A3', 'C4', 'E4'], ['F3', 'A3', 'C4'], ['C4', 'E4', 'G4'], ['G3', 'B3', 'D4']].map(c => c.map(N));
  const roots = ['A2', 'F2', 'C3', 'G2'].map(N);
  const mel = s => s.split(' ').map(t => { const [n, r, l] = t.split(':'); return { n: N(n), r: +r, l: +l }; });
  const melodyA = [
    mel('A4:0:4 C5:4:2 E5:6:2 A5:8:4 G5:12:2 E5:14:2'),
    mel('F5:0:4 E5:4:2 C5:6:2 A4:8:6 C5:14:2'),
    mel('E5:0:4 D5:4:2 C5:6:2 G4:8:4 C5:12:2 E5:14:2'),
    mel('D5:0:6 B4:6:2 G4:8:4 D5:12:2 B4:14:2'),
  ];
  const melodyB = [
    mel('E5:0:2 A5:2:2 C6:4:4 B5:8:2 A5:10:2 E5:12:4'),
    mel('F5:0:2 A5:2:2 C6:4:4 A5:8:4 F5:12:4'),
    mel('G5:0:2 E5:2:2 C5:4:4 E5:8:2 G5:10:2 C6:12:4'),
    mel('B5:0:4 A5:4:2 G5:6:2 D5:8:4 B4:12:4'),
  ];
  // what each bar plays: arp (pulsing chord), bass (kick + bass + arp), lead A/B with drums
  const plan = [];
  const add = (n, s) => { for (let i = 0; i < n; i++) plan.push(s); };
  add(5, { arp: 1 }); add(1, { arp: 1, kick: 'beat' });                 // part 1: stars
  add(8, { bass: 1, kick: 'beat' });                                     // part 2: fire
  add(8, { mel: melodyA, kick: 'half' });                                // part 3: the girl
  add(8, { mel: melodyB, kick: 'beat', snare: 1 });                      // part 4: tunnel
  add(8, { mel: melodyA, kick: 'beat', snare: 1 });                      // part 5: scroller
  add(8, { mel: melodyB, kick: 'beat', snare: 1, hat: 1 });
  add(4, { bass: 1, kick: 'beat' });
  add(4, { mel: melodyA, kick: 'half' });
  add(8, { mel: melodyB, kick: 'beat', snare: 1, hat: 1 });
  add(6, { arp: 1 }); add(1, { arp: 1, end: 1 }); add(1, { silent: 1 }); // part 6: greetings
  if (plan.length !== BARS) throw new Error(`song plan has ${plan.length} bars`);

  const ticks = [];
  plan.forEach((p, bar) => {
    const ch = chords[bar % 4], root = roots[bar % 4];
    const notes = p.mel ? p.mel[bar % 4] : [];
    for (let row = 0; row < 16; row++) for (let k = 0; k < 7; k++) {
      const t = bar * BAR + row * 7 + k;
      let f = 0;
      const arp = () => hz(ch[(t >> 1) % 3] + 12);
      if (p.silent) f = 0;
      else if (p.arp) {
        if (p.end) f = row < 12 ? (k < 6 ? hz(N('A4')) * (1 + 0.006 * Math.sin(t * 0.7)) : 0) : 0;
        else f = row % 2 === 0 && k < 5 ? arp() : 0;
      } else {
        const note = notes.find(n => row >= n.r && row < n.r + n.l);
        if (p.bass) f = row % 4 === 0 ? (k >= 2 && k < 5 ? hz(root) : 0) : (k < 5 ? arp() : 0);
        else if (note) {
          const last = row === note.r + note.l - 1;
          f = last && k === 6 ? 0 : hz(note.n) * (row > note.r ? 1 + 0.007 * Math.sin(t * 0.9) : 1);
        }
        if (p.hat && row % 4 === 2 && k === 0) f = 7200;
      }
      const kickRow = p.kick === 'beat' ? row % 4 === 0 : p.kick === 'half' ? row % 8 === 0 : false;
      if (kickRow && k < 2) f = [190, 95][k];
      if (p.snare && row % 8 === 4 && k < 2) f = 1800 + rnd() * 2600;
      ticks.push(f ? Math.round(1193182 / f) : 0);
    }
  });
  const song = Buffer.alloc(ticks.length * 2);
  ticks.forEach((v, i) => song.writeUInt16LE(v, i * 2));
  writeFileSync(join(gen, 'song.bin'), song);
  inc += `SONG_LEN equ ${ticks.length}\n`;

  writeFileSync(join(gen, 'data.inc'), inc);
};

function chunks(a, n) { const out = []; for (let i = 0; i < a.length; i += n) out.push(a.slice(i, i + n)); return out; }
