// os/build.mjs · build every bootable disk in os/programs/*
//   npm run os                 all disks
//   node os/build.mjs player   just one
//
// shared:     os/include/sine.inc (generated), public/os/vgafont.bin (the VGA font ROM)
// per disk:   os/programs/<id>/program.json, main.asm
//   assets.mjs (optional)   export default async ({ dir, gen, root }) => {}, runs before NASM,
//                           writes generated files into <dir>/gen/ for %include / incbin
//   "fs": true              a 7FS filesystem from <dir>/fs/ is packed right after the binary
//   "drive": "floppy"       the image is padded to a 1.44 MB floppy and boots as drive 00h
// output:     public/os/<image>, public/os/<id>.json (listing + symbols), public/os/<id>.asm,
//             public/os/disks.json (the boot menu)
import { execFileSync } from 'node:child_process';
import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const os = join(root, 'os'), out = join(root, 'public', 'os'), include = join(os, 'include');
mkdirSync(out, { recursive: true }); mkdirSync(include, { recursive: true });
await import(pathToFileURL(join(root, 'src', 'lib', 'cpu8086.js')).href);
const { CP437 } = globalThis.X86;
const ORG = 0x7C00, FLOPPY = 1474560;

// ---- shared: sine table (NASM has no floating point) and the font ROM ----
const sine = Array.from({ length: 256 }, (_, i) => Math.round(31.5 + 31.5 * Math.sin(i / 256 * 2 * Math.PI)));
writeFileSync(join(include, 'sine.inc'), '; generated by os/build.mjs: 256 steps of sin, 0..63\n' +
  Array.from({ length: 16 }, (_, r) => '        db ' + sine.slice(r * 16, r * 16 + 16).join(', ')).join('\n') + '\n');

const glyphs = new Map(readFileSync(join(os, 'font', 'unscii-16.hex'), 'latin1').split(/\r?\n/)
  .filter(Boolean).map(l => { const [cp, bits] = l.split(':'); return [parseInt(cp, 16), bits]; }));
// the four CP437 glyphs unscii-16 has no drawing for, drawn here in the IBM VGA style (8x16, hex rows)
const FALLBACK = {
  0x263C: '000000001818db3c e73cdb1818000000', // ☼
  0x2302: '0000000010386cc6 c6c6fe0000000000', // ⌂
  0x2310: '000000000000fec0 c0c0000000000000', // ⌐
  0x2219: '0000000000000018 1800000000000000', // ∙
};
const rom = Buffer.alloc(4096);
[...CP437].forEach((ch, i) => {
  if (i === 0 || i === 0x20 || i === 0xFF) return;
  const bits = glyphs.get(ch.codePointAt(0)) || FALLBACK[ch.codePointAt(0)]?.replace(' ', '');
  if (bits && bits.length === 32) Buffer.from(bits, 'hex').copy(rom, i * 16);
});
writeFileSync(join(out, 'vgafont.bin'), rom);

// ---- NASM listing -> lines + symbols for the debugger ----
function parseListing(file) {
  const lines = [], symbols = {}, pending = [];
  let global = '';
  for (const raw of readFileSync(file, 'latin1').split(/\r?\n/)) {
    const m = raw.match(/^\s*(\d+)\s(<\d+>)?(?:\s?([0-9A-F]{8})\s([0-9A-F\[\]\(\)]+)(-?))?\s*(.*)$/);
    if (!m) continue;
    const [, n, inc, off, hex, cont, text] = m;
    if (cont === '-' && !text) continue;
    const a = off ? ORG + parseInt(off, 16) : null;
    if (!inc) {
      const lab = text.match(/^([A-Za-z_.$?@][\w.$?@]*):/) || text.match(/^([A-Za-z_][\w$?@]*)\s+(?:db|dw|dd|times|equ)\b/);
      if (lab && !/\bequ\b/.test(text)) {
        const name = lab[1].startsWith('.') ? global + lab[1] : lab[1];
        if (!lab[1].startsWith('.')) global = lab[1];
        if (a !== null) symbols[a] ??= name; else pending.push(name);
      }
      if (a !== null && pending.length) { for (const p of pending.splice(0)) symbols[a] ??= p; }
      if (lines.length && lines[lines.length - 1].n === +n && !lines[lines.length - 1].inc) continue;
      lines.push({ n: +n, a, b: hex ? hex.replace(/[\[\]\(\)]/g, '').slice(0, 12) : '', s: text });
    }
  }
  return { lines, symbols };
}

// ---- 7FS: one directory sector of 16-byte entries, then sector-aligned files ----
function pack7FS(dir, firstLba, extra = []) {
  const COLORS = { TXT: 0x0B, ASM: 0x0E };
  const files = readdirSync(dir).sort().map(name => ({ name, data: readFileSync(join(dir, name)) })).concat(extra);
  const table = Buffer.alloc(512), chunks = [];
  let lba = firstLba + 1;
  files.forEach((f, i) => {
    const [base, ext = ''] = f.name.toUpperCase().split('.');
    if (base.length > 8 || ext.length > 3) throw new Error(`not an 8.3 name: ${f.name}`);
    if (f.data.length > 0xFFFF) throw new Error(`${f.name} is too big for 7FS`);
    table.write(base.padEnd(8) + ext.padEnd(3), i * 16, 'latin1');
    table[i * 16 + 11] = COLORS[ext] ?? 0x07;
    table.writeUInt16LE(lba, i * 16 + 12);
    table.writeUInt16LE(f.data.length, i * 16 + 14);
    const padded = Buffer.alloc(Math.ceil(f.data.length / 512) * 512); f.data.copy(padded);
    chunks.push(padded); lba += padded.length / 512;
  });
  return { data: Buffer.concat([table, ...chunks]), files: files.map(f => f.name) };
}

// ---- build ----
const only = process.argv[2];
const disks = [];
for (const id of readdirSync(join(os, 'programs')).sort()) {
  const dir = join(os, 'programs', id);
  if (!existsSync(join(dir, 'program.json'))) continue;
  const meta = JSON.parse(readFileSync(join(dir, 'program.json'), 'utf8'));
  disks.push(meta);
  if (only && only !== id) continue;

  const gen = join(dir, 'gen');
  if (existsSync(join(dir, 'assets.mjs'))) {
    mkdirSync(gen, { recursive: true });
    const mod = await import(pathToFileURL(join(dir, 'assets.mjs')).href + '?t=' + Date.now());
    await mod.default({ dir, gen, root, CP437 });
  }
  const bin = join(dir, 'gen', 'main.bin'), lst = join(dir, 'gen', 'main.lst');
  mkdirSync(gen, { recursive: true });
  try {
    execFileSync('nasm', ['-f', 'bin', '-i', include + '/', '-i', dir + '/', '-i', gen + '/', join(dir, 'main.asm'), '-o', bin, '-l', lst], { stdio: 'inherit' });
  } catch {
    console.error(`\n${id}: nasm failed (is it installed? scoop install nasm / apt install nasm)\n`);
    process.exit(1);
  }
  let image = readFileSync(bin);
  if (image[510] !== 0x55 || image[511] !== 0xAA) throw new Error(`${id}: boot signature 55AA missing`);
  let files = [];
  if (meta.fs) {
    if (image.length % 512) throw new Error(`${id}: binary must be whole sectors before 7FS`);
    const fs = pack7FS(join(dir, 'fs'), image.length / 512, [{ name: 'SOURCE.ASM', data: readFileSync(join(dir, 'main.asm')) }]);
    image = Buffer.concat([image, fs.data]); files = fs.files;
  }
  const size = meta.drive === 'floppy' ? FLOPPY : Math.ceil(image.length / 512) * 512;
  if (image.length > size) throw new Error(`${id}: image is bigger than a floppy`);
  const padded = Buffer.alloc(size); image.copy(padded);
  writeFileSync(join(out, meta.image), padded);
  copyFileSync(join(dir, 'main.asm'), join(out, `${id}.asm`));
  const { lines, symbols } = parseListing(lst);
  writeFileSync(join(out, `${id}.json`), JSON.stringify({ id, size, files, symbols, lines }));
  meta.size = size;
  console.log(`${id.padEnd(9)} ${meta.image.padEnd(14)} ${String(size).padStart(8)} bytes · ${Object.keys(symbols).length} symbols${files.length ? ' · 7FS: ' + files.join(' ') : ''}`);
}

// external disks (ELKS...) are described in os/external/*.json and fetched by os/fetch-external.mjs
const extDir = join(os, 'external');
if (existsSync(extDir)) for (const f of readdirSync(extDir).filter(f => f.endsWith('.json')).sort()) {
  const meta = JSON.parse(readFileSync(join(extDir, f), 'utf8'));
  if (existsSync(join(out, meta.image))) disks.push({ ...meta, external: true });
}
for (const d of disks) if (!d.size && existsSync(join(out, d.image))) d.size = readFileSync(join(out, d.image)).length;
const order = ['intro', '7os', 'player', 'maze', 'gui', 'snake', 'invaders', 'panic', 'elks'];   // the first one boots by default
disks.sort((a, b) => (order.indexOf(a.id) + 99) % 99 - (order.indexOf(b.id) + 99) % 99);
writeFileSync(join(out, 'disks.json'), JSON.stringify(disks.map(({ id, title, image, drive, description, keys, size, external, license, source }) =>
  ({ id, title, image, drive: drive || 'hdd', description, keys, size, external: !!external, license, source })), null, 2));
