// os/build.mjs · build almo7aya.img
//   npm run os
//  1. writes os/sine.inc (NASM has no floating point)
//  2. assembles os/almo7aya.asm with NASM: boot sector + kernel = 32 sectors
//  3. packs os/fs/* plus the OS's own source into 7FS at LBA 32
//  4. writes public/os/almo7aya.img and src/data/listing.json (for the debugger)
import { execFileSync } from 'node:child_process';
import { copyFileSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const os = join(root, 'os'), out = join(root, 'public', 'os');
const kernelBin = join(os, 'kernel.bin'), lst = join(os, 'almo7aya.lst'), img = join(out, 'almo7aya.img');
mkdirSync(out, { recursive: true });

// 1. sine table, 256 steps, 0..63 (the VGA DAC is 6 bits per channel)
const sine = Array.from({ length: 256 }, (_, i) => Math.round(31.5 + 31.5 * Math.sin(i / 256 * 2 * Math.PI)));
writeFileSync(join(os, 'sine.inc'), '; generated by build.mjs\n' +
  Array.from({ length: 16 }, (_, r) => '        db ' + sine.slice(r * 16, r * 16 + 16).join(', ')).join('\n') + '\n');

// 2. assemble
try {
  execFileSync('nasm', ['-f', 'bin', '-i', os + '/', join(os, 'almo7aya.asm'), '-o', kernelBin, '-l', lst], { stdio: 'inherit' });
} catch {
  console.error('\nnasm failed or is not installed. install it (scoop install nasm / apt install nasm) and retry.\n');
  process.exit(1);
}
const kernel = readFileSync(kernelBin);
const DIR_LBA = 32;
if (kernel.length !== DIR_LBA * 512) throw new Error(`kernel area is ${kernel.length} bytes, expected ${DIR_LBA * 512}`);
if (kernel[510] !== 0x55 || kernel[511] !== 0xAA) throw new Error('boot signature 55AA missing');

// 3. 7FS: one directory sector of 16-byte entries, then sector-aligned files
const COLORS = { TXT: 0x0B, ASM: 0x0E };
const files = readdirSync(join(os, 'fs')).sort().map(name => ({ name, data: readFileSync(join(os, 'fs', name)) }));
files.push({ name: 'SOURCE.ASM', data: readFileSync(join(os, 'almo7aya.asm')) });
const dir = Buffer.alloc(512), chunks = [];
let lba = DIR_LBA + 1;
files.forEach((f, i) => {
  const [base, ext = ''] = f.name.toUpperCase().split('.');
  if (base.length > 8 || ext.length > 3) throw new Error(`not an 8.3 name: ${f.name}`);
  if (f.data.length > 0xFFFF) throw new Error(`${f.name} is too big for 7FS`);
  const e = i * 16;
  dir.write(base.padEnd(8) + ext.padEnd(3), e, 'latin1');
  dir[e + 11] = COLORS[ext] ?? 0x07;
  dir.writeUInt16LE(lba, e + 12);
  dir.writeUInt16LE(f.data.length, e + 14);
  const sectors = Math.ceil(f.data.length / 512);
  const padded = Buffer.alloc(sectors * 512); f.data.copy(padded);
  chunks.push(padded); lba += sectors;
});
const image = Buffer.concat([kernel, dir, ...chunks]);
writeFileSync(img, image);
copyFileSync(join(os, 'almo7aya.asm'), join(out, 'almo7aya.asm'));

// 4. the NASM listing, so the debugger can show source next to the running code.
//    rows: "    12 00000010 BE[2300]           mov si, msg"; long db rows continue with '-'
const ORG = 0x7C00, lines = [];
for (const raw of readFileSync(lst, 'latin1').split(/\r?\n/)) {
  const m = raw.match(/^\s*(\d+)\s(?:\s?([0-9A-F]{8})\s([0-9A-F\[\]\(\)]+)(-?))?\s*(.*)$/);
  if (!m) continue;
  const [, n, off, hex, cont, text] = m;
  if (cont === '-' && !text) continue;
  if (lines.length && lines[lines.length - 1].n === +n) continue;
  if (/^\s*db \d+(, \d+)*$/.test(text) && +n > 0 && lines.length && /%include "sine/.test(lines[lines.length - 1].s)) continue;
  lines.push({ n: +n, a: off ? ORG + parseInt(off, 16) : null, b: hex ? hex.replace(/[\[\]\(\)]/g, '').slice(0, 12) : '', s: text });
}
mkdirSync(join(root, 'src', 'data'), { recursive: true });
writeFileSync(join(root, 'src', 'data', 'listing.json'), JSON.stringify({ size: image.length, files: files.map(f => f.name), lines }));

// 5. the VGA font ROM: unscii-16 (public domain) mapped to code page 437, 256 × 16 bytes
await import(pathToFileURL(join(root, 'src', 'lib', 'cpu8086.js')).href);
const glyphs = new Map(readFileSync(join(os, 'font', 'unscii-16.hex'), 'latin1').split(/\r?\n/)
  .filter(Boolean).map(l => { const [cp, bits] = l.split(':'); return [parseInt(cp, 16), bits]; }));
const rom = Buffer.alloc(4096);
let missing = 0;
[...globalThis.X86.CP437].forEach((ch, i) => {
  if (i === 0 || i === 0x20 || i === 0xFF) return;          // NUL, space, NBSP stay blank
  const bits = glyphs.get(ch.codePointAt(0));
  if (!bits || bits.length !== 32) { missing++; return; }
  Buffer.from(bits, 'hex').copy(rom, i * 16);
});
writeFileSync(join(out, 'vgafont.bin'), rom);
if (missing) console.warn(`vgafont.bin: ${missing} CP437 glyphs missing from unscii-16`);
console.log(`7OS: almo7aya.img ${image.length} bytes (${image.length / 512} sectors) · kernel ${DIR_LBA} sectors · 7FS ${files.length} files: ${files.map(f => f.name).join(' ')}`);
